name: Publish Latest

on:
  pull_request:
    branches: [ release ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Doesnt actually do anything"
        required: false
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Gradle Build library
        uses: gradle/gradle-build-action@v2.0-beta.1
        with:
          gradle-version: 7.1.1
          build-root-directory: $GITHUB_WORKSPACE
          arguments: :library:shadowJar
      
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
          
      - name: Create Release
        uses: ncipollo/release-action@v1.8.9
        with:
          artifacts: "library/build/libs/library*-all.jar"
          body: ${{ steps.Changelog.outputs.changelog }}
          allowUpdates: true
          prerelease: true
          tag: "latest"
          
